/**
 * Tests for server-side getServerTranslations with type safety
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  getServerTranslations,
  getTranslation,
  invalidateCache,
  loadTranslations,
} from "../utils/server";

describe("getServerTranslations (Type-Safe)", () => {
  const translations = {
    en: {
      welcome: "Welcome",
      logout: "Logout",
      greeting: "Hello {{name}}",
    },
    ko: {
      welcome: "환영합니다",
      logout: "로그아웃",
      greeting: "안녕하세요 {{name}}",
    },
  } as const;

  it("should return translations for specified language", () => {
    const dict = getServerTranslations("en", translations);

    expect(dict.welcome).toBe("Welcome");
    expect(dict.logout).toBe("Logout");
    expect(dict.greeting).toBe("Hello {{name}}");
  });

  it("should return translations for Korean language", () => {
    const dict = getServerTranslations("ko", translations);

    expect(dict.welcome).toBe("환영합니다");
    expect(dict.logout).toBe("로그아웃");
  });

  it("should fallback to English when language not found", () => {
    const dict = getServerTranslations("fr", translations);

    // Should fallback to English
    expect(dict.welcome).toBe("Welcome");
  });

  it("should handle empty translations object", () => {
    const emptyTranslations = {
      en: {},
      ko: {},
    } as const;

    const dict = getServerTranslations("en", emptyTranslations);

    expect(dict).toEqual({});
  });

  it("should preserve type information", () => {
    const dict = getServerTranslations("en", translations);

    // Type inference should work
    const welcome: string = dict.welcome;
    const logout: string = dict.logout;

    expect(welcome).toBe("Welcome");
    expect(logout).toBe("Logout");
  });

  it("should work with namespace translations", () => {
    const namespaceTranslations = {
      common: {
        en: {
          welcome: "Welcome",
          logout: "Logout",
        },
        ko: {
          welcome: "환영합니다",
          logout: "로그아웃",
        },
      },
      menu: {
        en: {
          home: "Home",
          about: "About",
        },
        ko: {
          home: "홈",
          about: "소개",
        },
      },
    } as const;

    // Flatten namespace structure for server-side usage
    const flatTranslations = {
      en: {
        ...namespaceTranslations.common.en,
        ...namespaceTranslations.menu.en,
      },
      ko: {
        ...namespaceTranslations.common.ko,
        ...namespaceTranslations.menu.ko,
      },
    };

    const dict = getServerTranslations("en", flatTranslations);

    expect(dict.welcome).toBe("Welcome");
    expect(dict.home).toBe("Home");
  });

  it("should merge flat namespace maps with later namespaces overriding earlier ones", () => {
    const dict = getServerTranslations("en", {
      common: {
        save: "Save",
        title: "Common title",
      },
      dashboard: {
        title: "Dashboard title",
      },
    });

    expect(dict.save).toBe("Save");
    expect(dict.title).toBe("Dashboard title");
  });
});

describe("loadTranslations", () => {
  const originalCwd = process.cwd();
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "i18nexus-load-"));
    process.chdir(tempDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("loads legacy flat language JSON files without dynamic imports", async () => {
    fs.mkdirSync(path.join(tempDir, "locales"), { recursive: true });
    fs.writeFileSync(
      path.join(tempDir, "locales", "en.json"),
      JSON.stringify({ welcome: "Welcome" })
    );
    fs.writeFileSync(
      path.join(tempDir, "locales", "ko.json"),
      JSON.stringify({ welcome: "환영합니다" })
    );

    const translations = await loadTranslations("./locales");

    expect(translations.en.welcome).toBe("Welcome");
    expect(translations.ko.welcome).toBe("환영합니다");
  });

  it("loads namespaced language JSON files generated by i18nexus-tools", async () => {
    fs.mkdirSync(path.join(tempDir, "locales", "common"), {
      recursive: true,
    });
    fs.writeFileSync(
      path.join(tempDir, "locales", "common", "en.json"),
      JSON.stringify({ welcome: "Welcome" })
    );
    fs.writeFileSync(
      path.join(tempDir, "locales", "common", "ko.json"),
      JSON.stringify({ welcome: "환영합니다" })
    );

    const translations = await loadTranslations("./locales");
    const dict = getServerTranslations("ko", translations);

    expect(dict.welcome).toBe("환영합니다");
  });
});

describe("getTranslation server namespace fallback", () => {
  const originalCwd = process.cwd();
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "i18nexus-server-"));
    process.chdir(tempDir);
    invalidateCache();
  });

  afterEach(() => {
    process.chdir(originalCwd);
    invalidateCache();
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("should merge fallback namespace keys and let requested namespace override them", async () => {
    fs.mkdirSync(path.join(tempDir, "locales", "common"), {
      recursive: true,
    });
    fs.mkdirSync(path.join(tempDir, "locales", "dashboard"), {
      recursive: true,
    });
    fs.writeFileSync(
      path.join(tempDir, "i18nexus.config.json"),
      JSON.stringify({
        localesDir: "./locales",
        defaultLanguage: "en",
        fallbackNamespace: "common",
      })
    );
    fs.writeFileSync(
      path.join(tempDir, "locales", "common", "en.json"),
      JSON.stringify({
        save: "Save",
        title: "Common title",
      })
    );
    fs.writeFileSync(
      path.join(tempDir, "locales", "dashboard", "en.json"),
      JSON.stringify({
        title: "Dashboard title",
      })
    );

    const { t, dict, translations, namespace } = await getTranslation(
      "dashboard",
      {
        language: "en",
        disableCache: true,
      }
    );

    expect(namespace).toBe("dashboard");
    expect(t("save")).toBe("Save");
    expect(t("title")).toBe("Dashboard title");
    expect(dict.save).toBe("Save");
    expect(dict.title).toBe("Dashboard title");
    expect(translations.common.save).toBe("Save");
    expect(translations.dashboard.title).toBe("Dashboard title");
  });

  it("should warn when i18nexus/server finds an unsupported JS config", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation();

    fs.writeFileSync(
      path.join(tempDir, "i18nexus.config.js"),
      `export default { localesDir: "./messages" };`
    );
    fs.mkdirSync(path.join(tempDir, "locales", "common"), {
      recursive: true,
    });
    fs.writeFileSync(
      path.join(tempDir, "locales", "common", "en.json"),
      JSON.stringify({
        title: "Common title",
      })
    );

    const { t } = await getTranslation("common", {
      language: "en",
      disableCache: true,
    });

    expect(t("title")).toBe("Common title");
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("i18nexus.config.js is ignored")
    );

    warnSpy.mockRestore();
  });
});

describe("translation cache source isolation", () => {
  it("isolates folders and invalidates matching namespace/language across folders", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "i18n-cache-sources-"));
    const write = (source: string, title: string) => {
      const namespaceDir = path.join(dir, source, "common");
      fs.mkdirSync(namespaceDir, { recursive: true });
      fs.writeFileSync(
        path.join(namespaceDir, "en.json"),
        JSON.stringify({ title })
      );
    };
    const read = (source: string) =>
      getTranslation("common", {
        language: "en",
        localesDir: path.join(dir, source),
      });
    try {
      invalidateCache();
      write("A", "First");
      write("B", "Second");
      expect((await read("A")).t("title")).toBe("First");
      expect((await read("B")).t("title")).toBe("Second");
      write("A", "Updated A");
      write("B", "Updated B");
      expect((await read("A")).t("title")).toBe("First");
      invalidateCache("common", "en");
      expect((await read("A")).t("title")).toBe("Updated A");
      expect((await read("B")).t("title")).toBe("Updated B");
    } finally {
      invalidateCache();
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
